### PR TITLE
fix: enable configuration through setup call

### LINKED ISSUE #36: Unable to change configuration with `setup({...})`
According to the documentation we should be able to modify the default picker options with the `require("window-picker").setup({...})` call and then supply single use overrides on top of this with the `require("window-picker").pick_window({...})` call. This seems to have been missed in the implementation as `require("window-picker").setup()` doesn't do anything:

https://github.com/s1n7ax/nvim-window-picker/blob/d3e26ba70dcf3248b2d8a9a9cb6e5ce2e3863bb8/lua/window-picker/init.lua#L42

### PR DESCRIPTION
**Pull request by mehalter**
Resolves #36

### CODE REVIEW

**Comment by mehalter** [comment]
@s1n7ax sorry to bother, but just wanted to bump this PR to fix the issue for running `setup`

**Comment by assistcontrol** [comment]
@s1n7ax Please merge this PR. `.setup()` is 100% broken and has been for weeks.

**Comment by s1n7ax** [comment]
Thanks!

**Comment by mehalter** [comment]
Thanks for merging @s1n7ax ! Do you have plans on tagging a 2.0 release as well just to make it available for people who track semantic versioning with a plugin manager like Lazy?

**Comment by mehalter** [comment]
Since you are following conventional commit messages I could also help out and add some automation for tagging releases. I am doing it with a couple other repos/Neovim plugins as well

**Comment by s1n7ax** [comment]
It would be amazing if you could automate it. At the moment I don't have access to a computer so it will take at least a week to release this. Thanks!

**Pull request merged**
